import type { Metadata } from 'next';
import { ReactNode } from 'react';
import '../styles/globals.scss';
import QueryProvider from '@event-mobile-front/providers/QueryProvider';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <QueryProvider>{children}</QueryProvider>
      </body>
    </html>
  );
}
